// =================================================================
// 🔸 LANGUAGE STRINGS
// =================================================================

const allStrings = {
    // ================== POLISH (PL) ==================
    pl: {
        metaTitle: "HoszMet - Nowoczesne Konstrukcje Stalowe",
        metaDescription: "HoszMet to lider w branży stalowej. Oferujemy kompleksowe usługi związane z montażem konstrukcji stalowych, spawaniem i zabudową płytami warstwowymi.",
        metaKeywords: "konstrukcje stalowe, montaż hal, spawanie, płyty warstwowe, HoszMet, Sośnicowice",
        phone: "697 232 228",
        videoNotSupported: "Twoja przeglądarka nie obsługuje tagu wideo.",
        heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Trwałość i Nowoczesność w Stali',
        heroSubtitle: 'Projektujemy, produkujemy i montujemy konstrukcje stalowe najwyższej jakości, dopasowane do Twoich potrzeb.',
        toggleVideoBtn_On: "Wyłącz wideo i pokaż realizacje",
        toggleVideoBtn_Off: "Włącz wideo",
        aboutUsTitle: "O nas",
        aboutUsText: "Firma HoszMet to lokalny lider w branży stalowej. Projektujemy, wykonujemy i montujemy konstrukcje stalowe, dopasowane do Twoich potrzeb. Zabudowujemy płytą warstwową i blachą trapezową. Działamy na rynku od wielu lat, łącząc doświadczenie z nowoczesnymi rozwiązaniami technologicznymi.",
        offerTitle: "Nasza oferta",
        offerItems: [
            { icon: "fas fa-building-user", title: "Montaż konstrukcji stalowych", text: "Specjalizujemy się w profesjonalnym montażu hal, magazynów i innych obiektów opartych na konstrukcjach stalowych." },
            { icon: "fas fa-tools", title: "Spawanie i prefabrykacja", text: "Wykonujemy trwałe elementy stalowe na zamówienie, gotowe do montażu na miejscu inwestycji." },
            { icon: "fas fa-clone", title: "Płyty Warstwowe i Blachy", text: "Zabudowujemy konstrukcje płytą warstwową i blachą trapezową, zapewniając trwałość i estetykę." },
            { icon: "fas fa-headset", title: "Doradztwo techniczne", text: "Nasi eksperci pomogą w doborze optymalnych rozwiązań i materiałów dla Twojego projektu." }
        ],
        contactTitle: "Kontakt",
        contactAddress: "ul. Powstańców 34<br>44-153 Sośnicowice",
        contactAddressBoxLine1: "ul. Powstańców 34",
        contactAddressBoxLine2: "44-153 Sośnicowice",
        contactCountry: "",
        contactNIP: "NIP: 9691525594",
        locationTitle: "Lokalizacja",
        locationMapAlt: "Mapa dojazdu do siedziby firmy HoszMet",
        footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Projekt i Realizacja: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Wszelkie prawa zastrzeżone.",
        footerPrivacy: "Strona wykorzystuje pliki cookies w celu zapewnienia najwyższej jakości usług. Dalsze korzystanie z witryny oznacza zgodę na ich użycie. Szanujemy Twoją prywatność.",
        backToTopAria: "Powrót do góry",
        loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Wystąpił błąd ładowania.<br>Prosimy odświeżyć stronę.',
        // TŁUMACZENIA GALERII / GALLERY TRANSLATIONS
        galleryButtonAria: "Otwórz galerię",
        galleryTitle: "Galeria",
        galleryShuffleAria: "Przetasuj zdjęcia",
        galleryPlayAria: "Uruchom pokaz slajdów",
        galleryCloseAria: "Zamknij galerię",
        galleryPrevAria: "Poprzednie zdjęcie",
        galleryNextAria: "Następne zdjęcie",
        galleryPhotoCounter: "Zdjęcie",
        galleryPhotoOf: "z",
        seeOurProjects: "Zobacz nasze realizacje"
    },
    // ================== ENGLISH (US) ==================
    us: {
        metaTitle: "HoszMet - Modern Steel Structures",
        metaDescription: "HoszMet is a leader in the steel industry. We offer comprehensive services related to the assembly of steel structures, welding, and sandwich panel cladding.",
        metaKeywords: "steel structures, hall assembly, welding, sandwich panels, HoszMet, Sośnicowice",
        phone: "+48 697 232 228",
        videoNotSupported: "Your browser does not support the video tag.",
        heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Durability and Modernity in Steel',
        heroSubtitle: 'We design, manufacture, and assemble the highest quality steel structures, tailored to your needs.',
        toggleVideoBtn_On: "Disable video and show projects",
        toggleVideoBtn_Off: "Enable video",
        aboutUsTitle: "About Us",
        aboutUsText: "HoszMet is a local leader in the steel industry. We design, manufacture, and assemble steel structures tailored to your needs. We clad structures with sandwich panels and trapezoidal sheets. We have been operating on the market for many years, combining experience with modern technological solutions.",
        offerTitle: "Our Offer",
        offerItems: [
            { icon: "fas fa-building-user", title: "Steel Structure Assembly", text: "We specialize in the professional assembly of halls, warehouses, and other facilities based on steel structures." },
            { icon: "fas fa-tools", title: "Welding and Prefabrication", text: "We produce durable custom-made steel elements, ready for assembly at the project site." },
            { icon: "fas fa-clone", title: "Sandwich Panels and Sheets", text: "We clad structures with sandwich panels and trapezoidal sheets, ensuring durability and aesthetics." },
            { icon: "fas fa-headset", title: "Technical Consulting", text: "Our experts will help you choose the optimal solutions and materials for your project." }
        ],
        contactTitle: "Contact",
        contactAddress: "34 Powstańców St.<br>44-153 Sośnicowice<br>Poland",
        contactAddressBoxLine1: "34 Powstańców St.",
        contactAddressBoxLine2: "44-153 Sośnicowice",
        contactCountry: "Poland",
        contactNIP: "TAX ID: PL9691525594",
        locationTitle: "Location",
        locationMapAlt: "Map with directions to the HoszMet headquarters",
        footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Design and Implementation: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. All rights reserved.",
        footerPrivacy: "This website uses cookies to ensure the highest quality of service. By continuing to use the site, you agree to their use. We respect your privacy.",
        backToTopAria: "Back to top",
        loaderError: '<i class="fas fa-exclamation-triangle"></i><br>An error occurred while loading.<br>Please refresh the page.',
        // TŁUMACZENIA GALERII / GALLERY TRANSLATIONS
        galleryButtonAria: "Open gallery",
        galleryTitle: "Gallery",
        galleryShuffleAria: "Shuffle photos",
        galleryPlayAria: "Start slideshow",
        galleryCloseAria: "Close gallery",
        galleryPrevAria: "Previous photo",
        galleryNextAria: "Next photo",
        galleryPhotoCounter: "Photo",
        galleryPhotoOf: "of",
        seeOurProjects: "See our projects"
    },
    // ================== GERMAN (DE) ==================
    de: {
        metaTitle: "HoszMet - Moderne Stahlkonstruktionen",
        metaDescription: "HoszMet ist ein führendes Unternehmen in der Stahlindustrie. Wir bieten umfassende Dienstleistungen in der Montage von Stahlkonstruktionen, Schweißarbeiten und der Verkleidung mit Sandwichplatten.",
        metaKeywords: "Stahlkonstruktionen, Hallenmontage, Schweißen, Sandwichplatten, HoszMet, Sośnicowice",
        phone: "+48 697 232 228",
        videoNotSupported: "Ihr Browser unterstützt das Video-Tag nicht.",
        heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Beständigkeit und Modernität in Stahl',
        heroSubtitle: 'Wir entwerfen, fertigen und montieren hochwertigste Stahlkonstruktionen, die auf Ihre Bedürfnisse zugeschnitten sind.',
        toggleVideoBtn_On: "Video deaktivieren und Projekte anzeigen",
        toggleVideoBtn_Off: "Video aktivieren",
        aboutUsTitle: "Über uns",
        aboutUsText: "HoszMet ist ein lokaler Marktführer in der Stahlindustrie. Wir entwerfen, fertigen und montieren Stahlkonstruktionen, die auf Ihre Bedürfnisse zugeschnitten sind. Wir verkleiden Konstruktionen mit Sandwichplatten und Trapezblechen. Wir sind seit vielen Jahren auf dem Markt tätig und verbinden Erfahrung mit modernen technologischen Lösungen.",
        offerTitle: "Unser Angebot",
        offerItems: [
            { icon: "fas fa-building-user", title: "Montage von Stahlkonstruktionen", text: "Wir sind spezialisiert auf die professionelle Montage von Hallen, Lagerhäusern und anderen Objekten auf Basis von Stahlkonstruktionen." },
            { icon: "fas fa-tools", title: "Schweißen und Vorfertigung", text: "Wir fertigen langlebige Stahlelemente nach Maß, bereit zur Montage am Projektstandort." },
            { icon: "fas fa-clone", title: "Sandwichplatten und Bleche", text: "Wir verkleiden Konstruktionen mit Sandwichplatten und Trapezblechen und sorgen so für Langlebigkeit und Ästhetik." },
            { icon: "fas fa-headset", title: "Technische Beratung", text: "Unsere Experten helfen Ihnen bei der Auswahl der optimalen Lösungen und Materialien für Ihr Projekt." }
        ],
        contactTitle: "Kontakt",
        contactAddress: "Powstańców Str. 34<br>44-153 Sośnicowice<br>Polen",
        contactAddressBoxLine1: "Powstańców Str. 34",
        contactAddressBoxLine2: "44-153 Sośnicowice",
        contactCountry: "Polen",
        contactNIP: "USt-IdNr.: PL9691525594",
        locationTitle: "Standort",
        locationMapAlt: "Karte mit Anfahrt zum Hauptsitz von HoszMet",
        footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Design und Umsetzung: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Alle Rechte vorbehalten.",
        footerPrivacy: "Diese Webseite verwendet Cookies, um die höchste Servicequalität zu gewährleisten. Indem Sie die Seite weiterhin nutzen, stimmen Sie deren Verwendung zu. Wir respektieren Ihre Privatsphäre.",
        backToTopAria: "Zurück nach oben",
        loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Beim Laden ist ein Fehler aufgetreten.<br>Bitte laden Sie die Seite neu.',
        galleryButtonAria: "Galerie öffnen",
        galleryTitle: "Galerie",
        galleryShuffleAria: "Fotos mischen",
        galleryPlayAria: "Diashow starten",
        galleryCloseAria: "Galerie schließen",
        galleryPrevAria: "Vorheriges Foto",
        galleryNextAria: "Nächstes Foto",
        galleryPhotoCounter: "Foto",
        galleryPhotoOf: "von",
        seeOurProjects: "Sehen Sie sich unsere Projekte an"
    },
    // ================== CZECH (CZ) ==================
    cz: {
        metaTitle: "HoszMet - Moderní Ocelové Konstrukce",
        metaDescription: "HoszMet je lídrem v ocelářském průmyslu. Nabízíme komplexní služby v oblasti montáže ocelových konstrukcí, svařování a opláštění sendvičovými panely.",
        metaKeywords: "ocelové konstrukce, montáž hal, svařování, sendvičové panely, HoszMet, Sośnicowice",
        phone: "+48 697 232 228",
        videoNotSupported: "Váš prohlížeč nepodporuje značku videa.",
        heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Odolnost a Modernost v Oceli',
        heroSubtitle: 'Navrhujeme, vyrábíme a montujeme ocelové konstrukce nejvyšší kvality, přizpůsobené vašim potřebám.',
        toggleVideoBtn_On: "Vypnout video a zobrazit projekty",
        toggleVideoBtn_Off: "Zapnout video",
        aboutUsTitle: "O nás",
        aboutUsText: "Firma HoszMet je lokálním lídrem v ocelářském průmyslu. Navrhujeme, vyrábíme a montujeme ocelové konstrukce přizpůsobené vašim potřebám. Konstrukce oplášťujeme sendvičovými panely a trapézovými plechy. Na trhu působíme již mnoho let a spojujeme zkušenosti s moderními technologickými řešeními.",
        offerTitle: "Naše nabídka",
        offerItems: [
            { icon: "fas fa-building-user", title: "Montáž ocelových konstrukcí", text: "Specializujeme se na profesionální montáž hal, skladů a dalších objektů na bázi ocelových konstrukcí." },
            { icon: "fas fa-tools", title: "Svařování a prefabrikace", text: "Vyrábíme odolné ocelové prvky na zakázku, připravené k montáži na místě projektu." },
            { icon: "fas fa-clone", title: "Sendvičové panely a plechy", text: "Konstrukce oplášťujeme sendvičovými panely a trapézovými plechy, čímž zajišťujeme odolnost a estetiku." },
            { icon: "fas fa-headset", title: "Technické poradenství", text: "Naši odborníci vám pomohou vybrat optimální řešení a materiály pro váš projekt." }
        ],
        contactTitle: "Kontakt",
        contactAddress: "ul. Powstańców 34<br>44-153 Sośnicowice<br>Polsko",
        contactAddressBoxLine1: "ul. Powstańców 34",
        contactAddressBoxLine2: "44-153 Sośnicowice",
        contactCountry: "Polsko",
        contactNIP: "DIČ: PL9691525594",
        locationTitle: "Lokalita",
        locationMapAlt: "Mapa s trasou do sídla společnosti HoszMet",
        footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Návrh a realizace: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Všechna práva vyhrazena.",
        footerPrivacy: "Tato webová stránka používá soubory cookies k zajištění nejvyšší kvality služeb. Dalším používáním stránky souhlasíte s jejich použitím. Respektujeme vaše soukromí.",
        backToTopAria: "Zpět na začátek",
        loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Při načítání došlo k chybě.<br>Obnovte prosím stránku.',
        galleryButtonAria: "Otevřít galerii",
        galleryTitle: "Galerie",
        galleryShuffleAria: "Zamíchat fotografie",
        galleryPlayAria: "Spustit prezentaci",
        galleryCloseAria: "Zavřít galerii",
        galleryPrevAria: "Předchozí fotografie",
        galleryNextAria: "Další fotografie",
        galleryPhotoCounter: "Fotografie",
        galleryPhotoOf: "z",
        seeOurProjects: "Zobrazit naše projekty"
    },
    // ================== SLOVAK (SK) ==================
    sk: {
        metaTitle: "HoszMet - Moderné Oceľové Konštrukcie",
        metaDescription: "HoszMet je lídrom v oceliarskom priemysle. Ponúkame komplexné služby spojené s montážou oceľových konštrukcií, zváraním a opláštením sendvičovými panelmi.",
        metaKeywords: "oceľové konštrukcie, montáž hál, zváranie, sendvičové panely, HoszMet, Sośnicowice",
        phone: "+48 697 232 228",
        videoNotSupported: "Váš prehliadač nepodporuje video tag.",
        heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Trvanlivosť a Modernosť v Oceli',
        heroSubtitle: 'Navrhujeme, vyrábame a montujeme oceľové konštrukcie najvyššej kvality, prispôsobené vašim potrebám.',
        toggleVideoBtn_On: "Vypnúť video a zobraziť realizácie",
        toggleVideoBtn_Off: "Zapnúť video",
        aboutUsTitle: "O nás",
        aboutUsText: "Firma HoszMet je lokálnym lídrom v oceliarskom priemysle. Navrhujeme, vyrábame a montujeme oceľové konštrukcie prispôsobené vašim potrebám. Oplášťujeme sendvičovými panelmi a trapézovým plechom. Na trhu pôsobíme mnoho rokov, spájajúc skúsenosti s modernými technologickými riešeniami.",
        offerTitle: "Naša ponuka",
        offerItems: [
            { icon: "fas fa-building-user", title: "Montáž oceľových konštrukcií", text: "Špecializujeme sa na profesionálnu montáž hál, skladov a iných objektov založených na oceľových konštrukciách." },
            { icon: "fas fa-tools", title: "Zváranie a prefabrikácia", text: "Vyrábame odolné oceľové prvky na zákazku, pripravené na montáž na mieste investície." },
            { icon: "fas fa-clone", title: "Sendvičové Panely a Plechy", text: "Oplášťujeme konštrukcie sendvičovými panelmi a trapézovým plechom, čím zaisťujeme trvanlivosť a estetiku." },
            { icon: "fas fa-headset", title: "Technické poradenstvo", text: "Naši odborníci vám pomôžu vybrať optimálne riešenia a materiály pre váš projekt." }
        ],
        contactTitle: "Kontakt",
        contactAddress: "ul. Powstańców 34<br>44-153 Sośnicowice<br>Poľsko",
        contactAddressBoxLine1: "ul. Powstańców 34",
        contactAddressBoxLine2: "44-153 Sośnicowice",
        contactCountry: "Poľsko",
        contactNIP: "IČ DPH: PL9691525594",
        locationTitle: "Lokalita",
        locationMapAlt: "Mapa s trasou do sídla spoločnosti HoszMet",
        footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Návrh a realizácia: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Všetky práva vyhradené.",
        footerPrivacy: "Táto webová stránka používa súbory cookie na zabezpečenie najvyššej kvality služieb. Pokračovaním v používaní stránky súhlasíte s ich používaním. Rešpektujeme vaše súkromie.",
        backToTopAria: "Späť na začiatok",
        loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Vyskytla sa chyba pri načítaní.<br>Prosím, obnovte stránku.',
        galleryButtonAria: "Otvoriť galériu",
        galleryTitle: "Galéria",
        galleryShuffleAria: "Premiešať fotografie",
        galleryPlayAria: "Spustiť prezentáciu",
        galleryCloseAria: "Zatvoriť galériu",
        galleryPrevAria: "Predchádzajúca fotografia",
        galleryNextAria: "Nasledujúca fotografia",
        galleryPhotoCounter: "Fotografia",
        galleryPhotoOf: "z",
        seeOurProjects: "Pozrite si naše realizácie"
    }
};

// ==========================================================================================
// KROK 2: UZUPEŁNIONE I POPRAWIONE JĘZYKI, KTÓRE WCZEŚNIEJ BYŁY NIEKOMPLETNE
// ==========================================================================================

allStrings.es = { // SPANISH
    ...allStrings.us,
    metaTitle: "HoszMet - Estructuras de Acero Modernas",
    metaDescription: "HoszMet es líder en la industria del acero. Ofrecemos servicios integrales relacionados con el montaje de estructuras de acero, soldadura y revestimiento con paneles sándwich.",
    metaKeywords: "estructuras de acero, montaje de naves, soldadura, paneles sándwich, HoszMet, Sośnicowice",
    videoNotSupported: "Su navegador no soporta la etiqueta de video.",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Durabilidad y Modernidad en Acero',
    heroSubtitle: 'Diseñamos, fabricamos y montamos estructuras de acero de la más alta calidad, adaptadas a sus necesidades.',
    toggleVideoBtn_On: "Desactivar video y mostrar proyectos",
    toggleVideoBtn_Off: "Activar video",
    aboutUsTitle: "Sobre Nosotros",
    aboutUsText: "HoszMet es un líder local en la industria del acero. Diseñamos, fabricamos y montamos estructuras de acero adaptadas a sus necesidades. Revestimos estructuras con paneles sándwich y chapas trapezoidales. Llevamos muchos años operando en el mercado, combinando la experiencia con soluciones tecnológicas modernas.",
    offerTitle: "Nuestra Oferta",
    offerItems: [
        { icon: "fas fa-building-user", title: "Montaje de Estructuras de Acero", text: "Nos especializamos en el montaje profesional de naves, almacenes y otras instalaciones basadas en estructuras de acero." },
        { icon: "fas fa-tools", title: "Soldadura y Prefabricación", text: "Producimos elementos de acero duraderos a medida, listos para su montaje en el lugar del proyecto." },
        { icon: "fas fa-clone", title: "Paneles Sándwich y Chapas", text: "Revestimos estructuras con paneles sándwich y chapas trapezoidales, garantizando durabilidad y estética." },
        { icon: "fas fa-headset", title: "Consultoría Técnica", text: "Nuestros expertos le ayudarán a elegir las soluciones y materiales óptimos para su proyecto." }
    ],
    contactTitle: "Contacto",
    contactAddress: "C/ Powstańców, 34<br>44-153 Sośnicowice<br>Polonia",
    contactAddressBoxLine1: "C/ Powstańców, 34",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "Polonia",
    contactNIP: "NIF: PL9691525594",
    locationTitle: "Ubicación",
    locationMapAlt: "Mapa con indicaciones para llegar a la sede de HoszMet",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Diseño e Implementación: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Todos los derechos reservados.",
    footerPrivacy: "Este sitio web utiliza cookies para garantizar la más alta calidad de servicio. Al continuar utilizando el sitio, usted acepta su uso. Respetamos su privacidad.",
    backToTopAria: "Volver arriba",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Ocurrió un error al cargar.<br>Por favor, actualice la página.',
    galleryButtonAria: "Abrir galería",
    galleryTitle: "Galería",
    galleryShuffleAria: "Mezclar fotos",
    galleryPlayAria: "Iniciar presentación",
    galleryCloseAria: "Cerrar galería",
    galleryPrevAria: "Foto anterior",
    galleryNextAria: "Siguiente foto",
    galleryPhotoCounter: "Foto",
    galleryPhotoOf: "de",
    seeOurProjects: "Ver nuestros proyectos"
};
allStrings.fr = { // FRENCH
    ...allStrings.us,
    metaTitle: "HoszMet - Structures en Acier Modernes",
    metaDescription: "HoszMet est un leader dans l'industrie de l'acier. Nous offrons des services complets liés à l'assemblage de structures en acier, à la soudure et au revêtement en panneaux sandwich.",
    metaKeywords: "structures en acier, montage de halls, soudure, panneaux sandwich, HoszMet, Sośnicowice",
    videoNotSupported: "Votre navigateur ne prend pas en charge la balise vidéo.",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Durabilité et Modernité en Acier',
    heroSubtitle: "Nous concevons, fabriquons et assemblons des structures en acier de la plus haute qualité, adaptées à vos besoins.",
    toggleVideoBtn_On: "Désactiver la vidéo et voir les projets",
    toggleVideoBtn_Off: "Activer la vidéo",
    aboutUsTitle: "À propos de nous",
    aboutUsText: "HoszMet est un leader local dans l'industrie de l'acier. Nous concevons, fabriquons et assemblons des structures en acier adaptées à vos besoins. Nous revêtons les structures avec des panneaux sandwich et des tôles trapézoïdales. Nous opérons sur le marché depuis de nombreuses années, alliant expérience et solutions technologiques modernes.",
    offerTitle: "Notre Offre",
    offerItems: [
        { icon: "fas fa-building-user", title: "Assemblage de Structures en Acier", text: "Nous sommes spécialisés dans l'assemblage professionnel de halls, d'entrepôts et d'autres installations basées sur des structures en acier." },
        { icon: "fas fa-tools", title: "Soudage et Préfabrication", text: "Nous produisons des éléments en acier durables sur mesure, prêts à être assemblés sur le site du projet." },
        { icon: "fas fa-clone", title: "Panneaux Sandwich et Tôles", text: "Nous revêtons les structures avec des panneaux sandwich et des tôles trapézoïdales, garantissant durabilité et esthétique." },
        { icon: "fas fa-headset", title: "Conseil Technique", text: "Nos experts vous aideront à choisir les solutions et les matériaux optimaux pour votre projet." }
    ],
    contactTitle: "Contact",
    contactAddress: "34, rue Powstańców<br>44-153 Sośnicowice<br>Pologne",
    contactAddressBoxLine1: "34, rue Powstańców",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "Pologne",
    contactNIP: "N° TVA: PL9691525594",
    locationTitle: "Emplacement",
    locationMapAlt: "Carte avec l'itinéraire vers le siège de HoszMet",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Conception et Réalisation: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Tous droits réservés.",
    footerPrivacy: "Ce site web utilise des cookies pour garantir la meilleure qualité de service. En continuant à utiliser le site, vous acceptez leur utilisation. Nous respectons votre vie privée.",
    backToTopAria: "Retour en haut",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Une erreur est survenue lors du chargement.<br>Veuillez rafraîchir la page.',
    galleryButtonAria: "Ouvrir la galerie",
    galleryTitle: "Galerie",
    galleryShuffleAria: "Mélanger les photos",
    galleryPlayAria: "Démarrer le diaporama",
    galleryCloseAria: "Fermer la galerie",
    galleryPrevAria: "Photo précédente",
    galleryNextAria: "Photo suivante",
    galleryPhotoCounter: "Photo",
    galleryPhotoOf: "sur",
    seeOurProjects: "Voir nos projets"
};
allStrings.it = { // ITALIAN
    ...allStrings.us,
    metaTitle: "HoszMet - Strutture Moderne in Acciaio",
    metaDescription: "HoszMet è leader nel settore dell'acciaio. Offriamo servizi completi relativi al montaggio di strutture in acciaio, saldatura e rivestimento con pannelli sandwich.",
    metaKeywords: "strutture in acciaio, montaggio di capannoni, saldatura, pannelli sandwich, HoszMet, Sośnicowice",
    videoNotSupported: "Il tuo browser non supporta il tag video.",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Durabilità e Modernità in Acciaio',
    heroSubtitle: "Progettiamo, produciamo e assembliamo strutture in acciaio di altissima qualità, su misura per le vostre esigenze.",
    toggleVideoBtn_On: "Disabilita video e mostra progetti",
    toggleVideoBtn_Off: "Abilita video",
    aboutUsTitle: "Chi siamo",
    aboutUsText: "HoszMet è un leader locale nel settore dell'acciaio. Progettiamo, produciamo e assembliamo strutture in acciaio su misura per le vostre esigenze. Rivestiamo le strutture con pannelli sandwich e lamiere grecate. Operiamo sul mercato da molti anni, combinando esperienza con soluzioni tecnologiche moderne.",
    offerTitle: "La nostra offerta",
    offerItems: [
        { icon: "fas fa-building-user", title: "Montaggio di Strutture in Acciaio", text: "Siamo specializzati nel montaggio professionale di capannoni, magazzini e altre strutture basate su costruzioni in acciaio." },
        { icon: "fas fa-tools", title: "Saldatura e Prefabbricazione", text: "Produciamo elementi in acciaio durevoli su misura, pronti per il montaggio in cantiere." },
        { icon: "fas fa-clone", title: "Pannelli Sandwich e Lamiere", text: "Rivestiamo le strutture con pannelli sandwich e lamiere grecate, garantendo durata ed estetica." },
        { icon: "fas fa-headset", title: "Consulenza Tecnica", text: "I nostri esperti vi aiuteranno a scegliere le soluzioni e i materiali ottimali per il vostro progetto." }
    ],
    contactTitle: "Contatti",
    contactAddress: "Via Powstańców, 34<br>44-153 Sośnicowice<br>Polonia",
    contactAddressBoxLine1: "Via Powstańców, 34",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "Polonia",
    contactNIP: "Partita IVA: PL9691525594",
    locationTitle: "Posizione",
    locationMapAlt: "Mappa con le indicazioni per la sede di HoszMet",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Progettazione e Realizzazione: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Tutti i diritti riservati.",
    footerPrivacy: "Questo sito web utilizza i cookie per garantire la massima qualità del servizio. Continuando a utilizzare il sito, acconsenti al loro uso. Rispettiamo la tua privacy.",
    backToTopAria: "Torna su",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Si è verificato un errore durante il caricamento.<br>Si prega di aggiornare la pagina.',
    galleryButtonAria: "Apri galleria",
    galleryTitle: "Galleria",
    galleryShuffleAria: "Mescola foto",
    galleryPlayAria: "Avvia presentazione",
    galleryCloseAria: "Chiudi galleria",
    galleryPrevAria: "Foto precedente",
    galleryNextAria: "Foto successiva",
    galleryPhotoCounter: "Foto",
    galleryPhotoOf: "di",
    seeOurProjects: "Guarda i nostri progetti"
};
allStrings.ua = { // UKRAINIAN
    ...allStrings.us,
    metaTitle: "HoszMet - Сучасні сталеві конструкції",
    metaDescription: "HoszMet – лідер у сталеливарній промисловості. Ми пропонуємо комплексні послуги, пов'язані з монтажем сталевих конструкцій, зварюванням та облицюванням сендвіч-панелями.",
    metaKeywords: "сталеві конструкції, монтаж ангарів, зварювання, сендвіч-панелі, HoszMet, Сосніцовіце",
    videoNotSupported: "Ваш браузер не підтримуuje тег video.",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Довговічність та Сучасність у Сталі',
    heroSubtitle: 'Ми проєктуємо, виготовляємо та монтуємо сталеві конструкції найвищої якості, адаптовані до ваших потреб.',
    toggleVideoBtn_On: "Вимкнути відео та показати проєкти",
    toggleVideoBtn_Off: "Увімкнути відео",
    aboutUsTitle: "Про нас",
    aboutUsText: "HoszMet – місцевий лідер у сталеливарній промисловості. Ми проєктуємо, виготовляємо та монтуємо сталеві конструкції, адаптовані до ваших потреб. Ми облицьовуємо конструкції сендвіч-панелями та трапецієподібним листом. Ми працюємо на ринку багато років, поєднуючи досвід із сучасними технологічними рішеннями.",
    offerTitle: "Наша пропозиція",
    offerItems: [
        { icon: "fas fa-building-user", title: "Монтаж сталевих конструкцій", text: "Ми спеціалізуємося на професійному монтажі ангарів, складів та інших об'єктів на основі сталевих конструкцій." },
        { icon: "fas fa-tools", title: "Зварювання та виготовлення", text: "Ми виробляємо довговічні сталеві елементи на замовлення, готові до монтажу на місці проєкту." },
        { icon: "fas fa-clone", title: "Сендвіч-панелі та листи", text: "Ми облицьовуємо конструкції сендвіч-панелями та трапецієподібним листом, забезпечуючи довговічність та естетику." },
        { icon: "fas fa-headset", title: "Технічні консультації", text: "Наші експерти допоможуть вам вибрати оптимальні рішення та матеріали для вашого проєкту." }
    ],
    contactTitle: "Контакти",
    contactAddress: "вул. Повстанців, 34<br>44-153 Сосніцовіце<br>Польща",
    contactAddressBoxLine1: "вул. Повстанців, 34",
    contactAddressBoxLine2: "44-153 Сосніцовіце",
    contactCountry: "Польща",
    contactNIP: "ІПН: PL9691525594",
    locationTitle: "Розташування",
    locationMapAlt: "Карта проїзду до штаб-квартири HoszMet",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Дизайн та реалізація: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Всі права захищено.",
    footerPrivacy: "Цей веб-сайт використовує файли cookie для забезпечення найвищої якості послуг. Продовжуючи користуватися сайтом, ви погоджуєтеся на їх використання. Ми поважаємо вашу конфіденційність.",
    backToTopAria: "Повернутися догори",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Сталася помилка під час завантаження.<br>Будь ласка, оновіть сторінку.',
    galleryButtonAria: "Відкрити галерею",
    galleryTitle: "Галерея",
    galleryShuffleAria: "Перемішати фотографії",
    galleryPlayAria: "Запустити слайд-шоу",
    galleryCloseAria: "Закрити галерею",
    galleryPrevAria: "Попереднє фото",
    galleryNextAria: "Наступне фото",
    galleryPhotoCounter: "Фото",
    galleryPhotoOf: "з",
    seeOurProjects: "Подивіться наші проєкти"
};
allStrings.br = { // BRAZILIAN PORTUGUESE
    ...allStrings.us,
    metaTitle: "HoszMet - Estruturas de Aço Modernas",
    metaDescription: "A HoszMet é líder na indústria siderúrgica. Oferecemos serviços abrangentes relacionados à montagem de estruturas de aço, soldagem e revestimento com painéis sanduíche.",
    metaKeywords: "estruturas de aço, montagem de galpões, soldagem, painéis sanduíche, HoszMet, Sośnicowice",
    videoNotSupported: "Seu navegador não suporta a tag de vídeo.",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Durabilidade e Modernidade em Aço',
    heroSubtitle: 'Projetamos, fabricamos e montamos estruturas de aço da mais alta qualidade, adaptadas às suas necessidades.',
    toggleVideoBtn_On: "Desativar vídeo e mostrar projetos",
    toggleVideoBtn_Off: "Ativar vídeo",
    aboutUsTitle: "Sobre Nós",
    aboutUsText: "A HoszMet é uma líder local na indústria siderúrgica. Projetamos, fabricamos e montamos estruturas de aço adaptadas às suas necessidades. Revestimos estruturas com painéis sanduíche e chapas trapezoidais. Atuamos no mercado há muitos anos, combinando experiência com soluções tecnológicas modernas.",
    offerTitle: "Nossa Oferta",
    offerItems: [
        { icon: "fas fa-building-user", title: "Montagem de Estruturas de Aço", text: "Somos especializados na montagem profissional de galpões, armazéns e outras instalações baseadas em estruturas de aço." },
        { icon: "fas fa-tools", title: "Soldagem e Pré-fabricação", text: "Produzimos elementos de aço duráveis sob medida, prontos para montagem no local do projeto." },
        { icon: "fas fa-clone", title: "Painéis Sanduíche e Chapas", text: "Revestimos estruturas com painéis sanduíche e chapas trapezoidais, garantindo durabilidade e estética." },
        { icon: "fas fa-headset", title: "Consultoria Técnica", text: "Nossos especialistas ajudarão você a escolher as soluções e materiais ideais para o seu projeto." }
    ],
    contactTitle: "Contato",
    contactAddress: "Rua Powstańców, 34<br>44-153 Sośnicowice<br>Polônia",
    contactAddressBoxLine1: "Rua Powstańców, 34",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "Polônia",
    contactNIP: "NIF: PL9691525594",
    locationTitle: "Localização",
    locationMapAlt: "Mapa com direções para a sede da HoszMet",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Projeto e Implementação: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Todos os direitos reservados.",
    footerPrivacy: "Este site usa cookies para garantir a mais alta qualidade de serviço. Ao continuar a usar o site, você concorda com o uso deles. Nós respeitamos sua privacidade.",
    backToTopAria: "Voltar ao topo",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Ocorreu um erro durante o carregamento.<br>Por favor, atualize a página.',
    galleryButtonAria: "Abrir galeria",
    galleryTitle: "Galeria",
    galleryShuffleAria: "Embaralhar fotos",
    galleryPlayAria: "Iniciar slideshow",
    galleryCloseAria: "Fechar galeria",
    galleryPrevAria: "Foto anterior",
    galleryNextAria: "Próxima foto",
    galleryPhotoCounter: "Foto",
    galleryPhotoOf: "de",
    seeOurProjects: "Veja nossos projetos"
};
allStrings.cn = { // CHINESE (SIMPLIFIED)
    ...allStrings.us,
    metaTitle: "HoszMet - 现代钢结构",
    metaDescription: "HoszMet 是钢铁行业的领导者。我们提供与钢结构组装、焊接和夹芯板覆盖相关的综合服务。",
    metaKeywords: "钢结构, 厂房搭建, 焊接, 夹芯板, HoszMet, Sośnicowice",
    videoNotSupported: "您的浏览器不支持视频标签。",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - 钢结构的耐用性与现代性',
    heroSubtitle: '我们设计、制造和组装最优质的钢结构，以满足您的需求。',
    toggleVideoBtn_On: "禁用视频并显示项目",
    toggleVideoBtn_Off: "启用视频",
    aboutUsTitle: "关于我们",
    aboutUsText: "HoszMet 是本地钢铁行业的领导者。我们根据您的需求设计、制造和组装钢结构。我们使用夹芯板和梯形钢板进行结构覆盖。我们已在市场上经营多年，将经验与现代技术解决方案相结合。",
    offerTitle: "我们的服务",
    offerItems: [
        { icon: "fas fa-building-user", title: "钢结构组装", text: "我们专业从事基于钢结构的厂房、仓库和其他设施的专业组装。" },
        { icon: "fas fa-tools", title: "焊接与预制", text: "我们生产耐用的定制钢构件，可在项目现场直接组装。" },
        { icon: "fas fa-clone", title: "夹芯板和钢板", text: "我们使用夹芯板和梯形钢板覆盖结构，确保耐用性和美观性。" },
        { icon: "fas fa-headset", title: "技术咨询", text: "我们的专家将帮助您为您的项目选择最佳的解决方案和材料。" }
    ],
    contactTitle: "联系方式",
    contactAddress: "Powstańców 街 34 号<br>44-153 Sośnicowice<br>波兰",
    contactAddressBoxLine1: "Powstańców 街 34 号",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "波兰",
    contactNIP: "税号: PL9691525594",
    locationTitle: "位置",
    locationMapAlt: "前往 HoszMet 总部的路线图",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. 设计与实施: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. 版权所有。",
    footerPrivacy: "本网站使用cookies以确保最高质量的服务。继续使用本网站即表示您同意我们使用cookies。我们尊重您的隐私。",
    backToTopAria: "返回顶部",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>加载时发生错误。<br>请刷新页面。',
    galleryButtonAria: "打开相册",
    galleryTitle: "相册",
    galleryShuffleAria: "随机播放照片",
    galleryPlayAria: "开始幻灯片",
    galleryCloseAria: "关闭相册",
    galleryPrevAria: "上一张照片",
    galleryNextAria: "下一张照片",
    galleryPhotoCounter: "照片",
    galleryPhotoOf: "/",
    seeOurProjects: "查看我们的项目"
};
allStrings.in = { // HINDI
    ...allStrings.us,
    metaTitle: "HoszMet - आधुनिक स्टील संरचनाएं",
    metaDescription: "HoszMet स्टील उद्योग में एक अग्रणी है। हम स्टील संरचनाओं की असेंबली, वेल्डिंग, और सैंडविच पैनल क्लैडिंग से संबंधित व्यापक सेवाएं प्रदान करते हैं।",
    metaKeywords: "स्टील संरचनाएं, हॉल असेंबली, वेल्डिंग, सैंडविच पैनल, HoszMet, Sośnicowice",
    videoNotSupported: "आपका ब्राउज़र वीडियो टैग का समर्थन नहीं करता है।",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - स्टील में स्थायित्व और आधुनिकता',
    heroSubtitle: 'हम आपकी आवश्यकताओं के अनुरूप उच्चतम गुणवत्ता वाली स्टील संरचनाओं का डिजाइन, निर्माण और संयोजन करते हैं।',
    toggleVideoBtn_On: "वीडियो अक्षम करें और परियोजनाएं दिखाएं",
    toggleVideoBtn_Off: "वीडियो सक्षम करें",
    aboutUsTitle: "हमारे बारे में",
    aboutUsText: "HoszMet स्टील उद्योग में एक स्थानीय नेता है। हम आपकी आवश्यकताओं के अनुरूप स्टील संरचनाओं का डिजाइन, निर्माण और संयोजन करते हैं। हम सैंडविच पैनल और ट्रेपेज़ॉइडल शीट के साथ संरचनाओं को कवर करते हैं। हम कई वर्षों से बाजार में काम कर रहे हैं, अनुभव को आधुनिक तकनीकी समाधानों के साथ जोड़ते हुए।",
    offerTitle: "हमारी पेशकश",
    offerItems: [
        { icon: "fas fa-building-user", title: "स्टील संरचना असेंबली", text: "हम स्टील संरचनाओं पर आधारित हॉल, गोदामों और अन्य सुविधाओं की पेशेवर असेंबली में विशेषज्ञ हैं।" },
        { icon: "fas fa-tools", title: "वेल्डिंग और प्रीफैब्रिकेशन", text: "हम टिकाऊ कस्टम-निर्मित स्टील तत्वों का उत्पादन करते हैं, जो परियोजना स्थल पर असेंबली के लिए तैयार हैं।" },
        { icon: "fas fa-clone", title: "सैंडविच पैनल और शीट्स", text: "हम सैंडविच पैनल और ट्रेपेज़ॉइडल शीट के साथ संरचनाओं को कवर करते हैं, जिससे स्थायित्व और सौंदर्य सुनिश्चित होता है।" },
        { icon: "fas fa-headset", title: "तकनीकी परामर्श", text: "हमारे विशेषज्ञ आपकी परियोजना के लिए इष्टतम समाधान और सामग्री चुनने में आपकी मदद करेंगे।" }
    ],
    contactTitle: "संपर्क",
    contactAddress: "34 पॉवस्टाńców स्ट्रीट<br>44-153 Sośnicowice<br>पोलैंड",
    contactAddressBoxLine1: "34 पॉवस्टाńców स्ट्रीट",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "पोलैंड",
    contactNIP: "टैक्स आईडी: PL9691525594",
    locationTitle: "स्थान",
    locationMapAlt: "HoszMet मुख्यालय के दिशा-निर्देशों के साथ नक्शा",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. डिजाइन और कार्यान्वयन: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. सर्वाधिकार सुरक्षित।",
    footerPrivacy: "यह वेबसाइट सेवा की उच्चतम गुणवत्ता सुनिश्चित करने के लिए कुकीज़ का उपयोग करती है। साइट का उपयोग जारी रखकर, आप उनके उपयोग के लिए सहमत हैं। हम आपकी गोपनीयता का सम्मान करते हैं।",
    backToTopAria: "वापस ऊपर",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>लोड करते समय एक त्रुटि हुई।<br>कृपया पृष्ठ को ताज़ा करें।',
    galleryButtonAria: "गैलरी खोलें",
    galleryTitle: "गैलरी",
    galleryShuffleAria: "तस्वीरें शफ़ल करें",
    galleryPlayAria: "स्लाइड शो शुरू करें",
    galleryCloseAria: "गैलरी बंद करें",
    galleryPrevAria: "पिछली तस्वीर",
    galleryNextAria: "अगली तस्वीर",
    galleryPhotoCounter: "तस्वीर",
    galleryPhotoOf: "/",
    seeOurProjects: "हमारी परियोजनाएं देखें"
};
allStrings.id = { // INDONESIAN
    ...allStrings.us,
    metaTitle: "HoszMet - Struktur Baja Modern",
    metaDescription: "HoszMet adalah pemimpin dalam industri baja. Kami menawarkan layanan komprehensif terkait perakitan struktur baja, pengelasan, dan pelapisan panel sandwich.",
    metaKeywords: "struktur baja, perakitan aula, pengelasan, panel sandwich, HoszMet, Sośnicowice",
    videoNotSupported: "Browser Anda tidak mendukung tag video.",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - Daya Tahan dan Modernitas dalam Baja',
    heroSubtitle: 'Kami merancang, memproduksi, dan merakit struktur baja kualitas tertinggi, yang disesuaikan dengan kebutuhan Anda.',
    toggleVideoBtn_On: "Nonaktifkan video dan tampilkan proyek",
    toggleVideoBtn_Off: "Aktifkan video",
    aboutUsTitle: "Tentang Kami",
    aboutUsText: "HoszMet adalah pemimpin lokal dalam industri baja. Kami merancang, memproduksi, dan merakit struktur baja yang disesuaikan dengan kebutuhan Anda. Kami melapisi struktur dengan panel sandwich dan lembaran trapesium. Kami telah beroperasi di pasar selama bertahun-tahun, menggabungkan pengalaman dengan solusi teknologi modern.",
    offerTitle: "Penawaran Kami",
    offerItems: [
        { icon: "fas fa-building-user", title: "Perakitan Struktur Baja", text: "Kami berspesialisasi dalam perakitan profesional aula, gudang, dan fasilitas lain yang berbasis struktur baja." },
        { icon: "fas fa-tools", title: "Pengelasan dan Prefabrikasi", text: "Kami memproduksi elemen baja custom yang tahan lama, siap untuk dirakit di lokasi proyek." },
        { icon: "fas fa-clone", title: "Panel Sandwich dan Lembaran", text: "Kami melapisi struktur dengan panel sandwich dan lembaran trapesium, memastikan daya tahan dan estetika." },
        { icon: "fas fa-headset", title: "Konsultasi Teknis", text: "Para ahli kami akan membantu Anda memilih solusi dan bahan yang optimal untuk proyek Anda." }
    ],
    contactTitle: "Kontak",
    contactAddress: "Jl. Powstańców 34<br>44-153 Sośnicowice<br>Polandia",
    contactAddressBoxLine1: "Jl. Powstańców 34",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "Polandia",
    contactNIP: "ID Pajak: PL9691525594",
    locationTitle: "Lokasi",
    locationMapAlt: "Peta dengan petunjuk arah ke kantor pusat HoszMet",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. Desain dan Implementasi: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. Hak cipta dilindungi undang-undang.",
    footerPrivacy: "Situs web ini menggunakan cookie untuk memastikan kualitas layanan tertinggi. Dengan terus menggunakan situs ini, Anda menyetujui penggunaannya. Kami menghormati privasi Anda.",
    backToTopAria: "Kembali ke atas",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>Terjadi kesalahan saat memuat.<br>Silakan segarkan halaman.',
    galleryButtonAria: "Buka galeri",
    galleryTitle: "Galeri",
    galleryShuffleAria: "Acak foto",
    galleryPlayAria: "Mulai slideshow",
    galleryCloseAria: "Tutup galeri",
    galleryPrevAria: "Foto sebelumnya",
    galleryNextAria: "Foto berikutnya",
    galleryPhotoCounter: "Foto",
    galleryPhotoOf: "dari",
    seeOurProjects: "Lihat proyek kami"
};
allStrings.jp = { // JAPANESE
    ...allStrings.us,
    metaTitle: "HoszMet - モダンな鋼構造",
    metaDescription: "HoszMetは鉄鋼業界のリーダーです。鉄骨構造の組み立て、溶接、サンドイッチパネルの外装に関する包括的なサービスを提供しています。",
    metaKeywords: "鉄骨構造, ホール組み立て, 溶接, サンドイッチパネル, HoszMet, Sośnicowice",
    videoNotSupported: "お使いのブラウザはビデオタグをサポートしていません。",
    heroTitle: '<span class="hero-hosz">Hosz</span><span class="hero-met">Met</span> - 鋼の耐久性と現代性',
    heroSubtitle: 'お客様のニーズに合わせた最高品質の鉄骨構造を設計、製造、組み立てます。',
    toggleVideoBtn_On: "ビデオを無効にしてプロジェクトを表示",
    toggleVideoBtn_Off: "ビデオを有効にする",
    aboutUsTitle: "会社概要",
    aboutUsText: "HoszMetは地元の鉄鋼業界のリーダーです。お客様のニーズに合わせた鉄骨構造を設計、製造、組み立てます。サンドイッチパネルと台形シートで構造物を覆います。私たちは長年市場で事業を展開しており、経験と現代の技術的ソリューションを組み合わせています。",
    offerTitle: "サービス内容",
    offerItems: [
        { icon: "fas fa-building-user", title: "鉄骨構造の組み立て", text: "私たちは、鉄骨構造に基づくホール、倉庫、その他の施設の専門的な組み立てを専門としています。" },
        { icon: "fas fa-tools", title: "溶接とプレハブ", text: "プロジェクト現場で組み立てる準備ができている、耐久性のあるカスタムメイドの鋼材を製造します。" },
        { icon: "fas fa-clone", title: "サンドイッチパネルとシート", text: "サンドイッチパネルと台形シートで構造物を覆い、耐久性と美観を確保します。" },
        { icon: "fas fa-headset", title: "技術コンサルティング", text: "私たちの専門家が、お客様のプロジェクトに最適なソリューションと材料を選択するお手伝いをします。" }
    ],
    contactTitle: "お問い合わせ",
    contactAddress: "Powstańców通り 34<br>44-153 Sośnicowice<br>ポーランド",
    contactAddressBoxLine1: "Powstańców通り 34",
    contactAddressBoxLine2: "44-153 Sośnicowice",
    contactCountry: "ポーランド",
    contactNIP: "納税者番号: PL9691525594",
    locationTitle: "所在地",
    locationMapAlt: "HoszMet本社への道順地図",
    footerCopyright: "© 2025 <a href='http://www.hoszmet.pl' target='_blank'>HoszMet</a>. デザインと実装: <a href='http://www.ade.pl' target='_blank'><strong>ade</strong></a>. 全著作権所有。",
    footerPrivacy: "このウェブサイトは、最高品質のサービスを保証するためにクッキーを使用しています。サイトの利用を継続することにより、その使用に同意したことになります。私たちはあなたのプライバシーを尊重します。",
    backToTopAria: "トップに戻る",
    loaderError: '<i class="fas fa-exclamation-triangle"></i><br>読み込み中にエラーが発生しました。<br>ページを更新してください。',
    galleryButtonAria: "ギャラリーを開く",
    galleryTitle: "ギャラリー",
    galleryShuffleAria: "写真をシャッフル",
    galleryPlayAria: "スライドショーを開始",
    galleryCloseAria: "ギャラリーを閉じる",
    galleryPrevAria: "前の写真",
    galleryNextAria: "次の写真",
    galleryPhotoCounter: "写真",
    galleryPhotoOf: "/",
    seeOurProjects: "プロジェクトを見る"
};

// Singapore uses English as a base
allStrings.sg = { 
    ...allStrings.us,
    galleryButtonAria: "Open gallery",
    galleryTitle: "Gallery",
    galleryShuffleAria: "Shuffle photos",
    galleryPlayAria: "Start slideshow",
    galleryCloseAria: "Close gallery",
    galleryPrevAria: "Previous photo",
    galleryNextAria: "Next photo",
    galleryPhotoCounter: "Photo",
    galleryPhotoOf: "of",
    seeOurProjects: "See our projects"
};